# Generated by Django 2.2.9 on 2020-07-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200719_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalblacklist',
            name='changed_by',
        ),
    ]
