# Generated by Django 2.2.9 on 2020-07-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200720_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_details',
            name='Fees_to_be_incurred_for_STS_Operations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
