# Generated by Django 2.2.9 on 2020-07-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200727_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='Agent_Company',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='Provider_company',
        ),
        migrations.RemoveField(
            model_name='historicalentry',
            name='Agent_Company',
        ),
        migrations.RemoveField(
            model_name='historicalentry',
            name='Provider_company',
        ),
    ]
