# Generated by Django 2.2.9 on 2020-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200728_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='degrees_latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='degrees_longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='minutes_latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='minutes_longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='seconds_latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='seconds_longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='degrees_latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='degrees_longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='minutes_latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='minutes_longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='seconds_latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='seconds_longitude',
            field=models.IntegerField(null=True),
        ),
    ]
