# Generated by Django 2.2.9 on 2020-08-01 13:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200730_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Cargos_permitted',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Oil', 'Oil'), ('LPG', 'LPG'), ('Chemicals', 'Chemicals'), ('LNG', 'LNG'), ('All cargoes permitted', 'All cargoes permitted')], max_length=1000, null=True),
        ),
    ]
